name: Sonar Continuos Integration
env:
  DOTNET_VERSION: '8.0.407'                     # la versión de .NET
  SONAR_ORG: 'Lab01CalidadSoftware'             # Nombre de la organización de sonar cloud
  SONAR_PROJECT: 'Brunoenr02_Lab01CalidadSoftware'  # Key ID del proyecto de sonar
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  sonarqube:
    name: Sonarqube Analisys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurando la versión de NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Configurar NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restaurar dependencias
        run: nuget restore

      - name: Instalar Scanner
        run: dotnet tool install -g dotnet-sonarscanner

      - name: Ejecutar pruebas
        run: |
          dotnet restore 
          dotnet test --collect:"XPlat Code Coverage;Format=opencover"
          dotnet-sonarscanner begin /k:"${{ env.SONAR_PROJECT }}" /o:"${{ env.SONAR_ORG }}" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="*/*/*/coverage.opencover.xml" /d:sonar.qualitygate.wait=true
          dotnet build
          dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

  release:
    name: Publicar Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Crear el paquete NuGet
        run: |
          dotnet pack Bank/Bank.Domain/Bank.Domain.csproj --configuration Release --output nupkg

      - name: Publicar en GitHub Packages
        run: |
          dotnet nuget push nupkg/*.nupkg \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source "https://nuget.pkg.github.com/Brunoenr02/index.json" \
            --skip-duplicate
